apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: uberrawdatatopic
  labels:
    strimzi.io/cluster: uber-cluster
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
 

